# Generated by Django 6.0.2 on 2026-03-11 21:45

import django.contrib.auth.models
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_remove_user_role_user_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.ActiveUserManager()),
                ('dm_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
