# Generated by Django 6.0.2 on 2026-02-28 00:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('address', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('birthday', models.DateField()),
                ('modality', models.CharField(choices=[('CLT', 'CLT'), ('SERVICE_PROVIDER', 'Prestador de Serviços')], default='CLT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
