# Generated by Django 6.0.2 on 2026-03-11 21:45

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_created_by_employee_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True, validators=[utils.validators.validate_phone]),
        ),
    ]
