# Generated by Django 6.0.2 on 2026-02-28 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INCOME', 'Entrada'), ('EXPENSE', 'Saida')], max_length=10)),
                ('category', models.CharField(choices=[('MONTHLY_FEE', 'Mensalidade'), ('STORE_SERVICE', 'Loja / Serviços'), ('LOGISTIC', 'Logística'), ('PAYROLL', 'Folha de Pagamento')], max_length=30)),
                ('payment_method', models.CharField(blank=True, choices=[('PIX', 'PIX'), ('CASH', 'Dinheiro'), ('CARD', 'Cartão')], max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
