# Generated by Django 6.0.2 on 2026-03-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_customer_transaction_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
