# Generated by Django 6.0.2 on 2026-03-11 21:45

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_birthday_customer_cpf_customer_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True, validators=[utils.validators.validate_phone]),
        ),
    ]
