# Generated by Django 6.0.2 on 2026-03-13 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_overdue',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='monthly_fee',
        ),
    ]
